title: "ym2151-log-play-server"
description: "ym2151-log-play-server"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/ym2151-log-play-server
